name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g. 1.0.0) or leave empty for auto
        required: false

jobs:
  release:
    uses: getsentry/craft/.github/workflows/release.yml@v2
    with:
      version: ${{ inputs.version }}
    secrets: inherit
